# Generated by Django 3.1.6 on 2021-02-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationprovider',
            name='accuracy_radius',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='locationprovider',
            name='geoname_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='locationprovider',
            name='registered_country_geoname_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='locationprovider',
            name='represented_country_geoname_id',
            field=models.IntegerField(null=True),
        ),
    ]
