# Generated by Django 3.1.6 on 2021-02-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_provider', '0002_auto_20210217_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationprovider',
            name='postal_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
