# Generated by Django 3.1.6 on 2021-02-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_provider', '0003_auto_20210217_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationprovider',
            name='is_anonymous_proxy',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='locationprovider',
            name='is_satellite_provider',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='locationprovider',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='locationprovider',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
